CREATE TABLE `CLASS_NUM` (
	`id` SERIAL NOT NULL,
	`SCHOOL_CD` CHAR(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
	`CLASS_NUM` VARCHAR(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
	PRIMARY KEY (`SCHOOL_CD`,`CLASS_NUM`)
);

CREATE TABLE `SCHOOL` (
	`id` SERIAL NOT NULL,
	`CD` CHAR(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
	`NAME` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
	PRIMARY KEY (`CD`)
);

CREATE TABLE `STUDENT` (
	`id` SERIAL NOT NULL,
	`NO` VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
	`NAME` VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
	`ENT_YEAR` INT(10) DEFAULT NULL,
	`CLASS_NUM` CHAR(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
	`IS_ATTEND` BOOLEAN DEFAULT TRUE,
	`SCHOOL_CD` CHAR(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
	PRIMARY KEY (`NO`)
);

CREATE TABLE `SUBJECT` (
	`id` SERIAL NOT NULL,
	`SCHOOL_CD` CHAR(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_german2_ci NOT NULL,
	`CD` CHAR(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
	`NAME` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
	PRIMARY KEY (`SCHOOL_CD`,`CD`)
);

CREATE TABLE `TEACHER` (
	`id` SERIAL NOT NULL,
	`TEACHER_ID` VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
	`PASSWORD` VARCHAR(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
	`NAME` VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
	`SCHOOL_CD` CHAR(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `TEST` (
	`id` SERIAL NOT NULL,
	`STUDENT_NO` VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
	`SUBJECT_CD` CHAR(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
	`SCHOOL_CD` CHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
	`NO` INT(10) NOT NULL,
	`POINT` INT(10) DEFAULT NULL,
	`CLASS_NUM` VARCHAR(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
	PRIMARY KEY (`STUDENT_NO`,`SUBJECT_CD`,`SCHOOL_CD`,`NO`)
);